name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y g++ libsqlite3-dev

      - name: Build project
        run: |
          mkdir -p build
          g++ -o build/my_project TICTACTOE_Final/*.cpp -l sqlite3 -I include

      - name: Run tests
        run: |
          ./build/my_project
