name: C++ Build and Test

on:
  push:  # This will now trigger on a push to any branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install G++ and Google Test
        run: sudo apt-get update && sudo apt-get install -y g++ cmake libgtest-dev

      - name: Compile Google Test
        run: |
          sudo cmake -E make_directory /usr/src/googletest/build
          sudo cmake -E chdir /usr/src/googletest/build cmake ..
          sudo cmake --build /usr/src/googletest/build
          sudo cmake --build /usr/src/googletest/build --target install

      - name: List files in the working directory
        run: ls -al

      - name: Compile and Link Project
        run: g++ -isystem /usr/include/gtest -I. -pthread Source.cpp -o tictactoe -lgtest -lgtest_main