name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install g++ and SQLite
        run: |
          choco install mingw
          choco install sqlite

      - name: Build project
        run: |
          mkdir build
          g++ -o build/my_project src/*.cpp -lsqlite3 -I include

      - name: Run tests
        run: |
          ./build/my_project
