name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
      - uses: actions/checkout@v2

      - name: Install g++
        run: |
          choco install mingw -y
          RefreshEnv

      - name: Install SQLite3
        run: |
          choco install sqlite -y
          RefreshEnv

      - name: Build
        run: g++ -o tictactoe Source.cpp -lsqlite3
